config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :leads
  
  patch '/leads/:id/edit(.:format)' => 'leads#contacted'
  post '/search' => 'leads#search'
  
  resources :users, only: [:index, :edit, :update, :destroy]

  root to: redirect('/leads') 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
    validates :first_name, :last_name, :phone, :email, presence: true
    validates :email, uniqueness: true, email: true
    
    scope :contacted, -> (contacted)  { where(contacted: true ) }
    scope :uncontacted, -> (uncontacted) { where(contacted: false ) }
    scope :first_name_contains, -> (first_name) { where("first_name like ?", "#{first_name}%")}
    scope :last_name_contains, -> (last_name) { where("last_name like ?", "#{last_name}%")}
    scope :email_contains, -> (email) { where("email like ?", "#{email}%")}
    
    scope :search, -> (search) { first_name_contains(search).or(last_name_contains(search)).or(email_contains(search)) }
   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
    before_action :authenticate_user!
    def index
        @leads = Lead.page(params[:page])
        
        filtered(params).each do |k, v|
           @leads = @leads.public_send(k, v) if v.present?
       end
    end
    
    def show
        @lead = Lead.find(params[:id])
    end
    
    def new
        @lead = Lead.new
    end
    
    def edit
        @lead = Lead.find(params[:id])
    end
    
    def create
        @lead = Lead.new(lead_params)
        if @lead.save
            redirect_to @lead
        else
            render 'new'
        end
    end
    
    def update
        @lead = Lead.find(params[:id])
        if @lead.update(lead_params)
            redirect_to @lead
        else
            render 'edit'
        end
    end
    
    def destroy
        @lead = Lead.find(params[:id])
        @lead.destroy
        redirect_to leads_path
    end
    
    def contacted
        @lead = Lead.find(params[:id])
        
        @lead.update(:contacted => true)
            redirect_to leads_path
    end
    
    def search
      search = params[:search]
      search_string =  search.to_str.gsub(' ', '&')
      redirect_to "/leads?search=#{search_string}"
    end
    
    private
        def lead_params
            params.require(:lead).permit(:first_name, :last_name, :phone, :email, :contacted)
        end
        
        def filtered(params)
          params.slice(:contacted, :uncontacted, :first_name_contains, :last_name_contains, :email_contains, :search)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_filter :ensure_admin!
    
    def index
        @users = User.page(params[:page])
    end
    
   def edit
        @user = User.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to users_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end
    
    private
        def user_params
            params.require(:user).permit(:name, :email, :admin)
        end
        
        def ensure_admin!
            unless current_user.admin?
                redirect_to root_path
                return false
            end
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sales Leads App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div style="text-align: right;">
    <li>
      <%= link_to('Sales Leads', leads_path) %>
    </li>
    <li>
      <%= link_to('Users', users_path) %>
    </li>
    
  <% if user_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
    </li>
  <% else %>
    <li>
      <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/leads/edit.html.erb
<div class="container">
    <div class="container">
        <h1>Update Lead</h1>
    </div>
    <div class="container">
    <%= form_for :lead, url: lead_path(@lead), html: {class: 'form-horizontal center'}, method: :patch do |f| %>
        
        <% if @lead.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@lead.errors.count, "error") %> prohibited
                this lead from being saved:
              </h2>
              <ul>
                <% @lead.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
         <% end %>
         
        <div class="form-group">
                <%= f.label :first_name, class: "col-md-2 control-label" %>
                <div class="col-md-8">
                    <%= f.text_field :first_name, class: "form-control" %>
                </div>
            </div>
            
            <div class="form-group">
                <%= f.label :last_name, class: "col-md-2 control-label" %>
                <div class="col-md-8">
                    <%= f.text_field :last_name, class: "form-control" %>
                </div>
            </div>
            
            <div class="form-group">
                <%= f.label :phone, class: "col-md-2 control-label" %>
                <div class="col-md-8">
                    <%= f.text_field :phone, class: "form-control" %>
                </div>
            </div>
            
            <div class="form-group">
                <%= f.label :email, class: "col-md-2 control-label" %>
                <div class="col-md-8">
                    <%= f.text_field :email, class: "form-control" %>
                </div>
            </div>
            
            <div class="form-group">
                <%= f.label :contacted, class: "col-md-2 control-label" %>
                <div class="col-md-8">
                    <%= f.check_box :contacted, class: "form-control" %>
                </div>
            </div>
            
        <%= f.submit class: "btn btn-primary " %>
    
        
        <% end %>
        
    <%= link_to 'Back', leads_path %>
   

app/views/leads/index.html.erb
<div class="container">
    <div class="container">
        <h1>All Leads </h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <%= link_to 'New Lead', new_lead_path, class: "btn btn-primary", role: "button" %>
            </div>
            <div class="col-md-6">
                <%= form_tag('/search') do %>
                      <%= label_tag(:search_name, "Search Names:") %>
                      <%= text_field_tag 'search' %>
                      <%= submit_tag('Search') %>
                <% end %>
            </div>
         </div>
    </div>
<div class="container">    
    <table class="table-condensed table-hover table-responsive">
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Phone Number</th>
        <th>Email Address</th>
        <th>Contacted?</th>
        <th colspan="2" style="text-align: right;">Filter by: <%= link_to 'Contacted', "/leads?contacted=true", class: "btn btn-warning btn-sm", role: "button" %></th>
        <th colspan="2"><%= link_to 'Uncontacted', "/leads?uncontacted=true", class: "btn btn-warning btn-sm", role: "button" %></th>
        
      <% @leads.each do |lead| %>
        <tr>
          <td><%= lead.first_name %></td>
          <td><%= lead.last_name %></td>
          <td><%= lead.phone %></td>
          <td><%= lead.email %></td>
          <td><%= lead.contacted? ? "yes" : "no" %></td>
           <td><%= link_to 'Set Contacted', edit_lead_path(lead), class: "btn btn-primary", role: "button", method: :patch %></td>
          <td><%= link_to 'Show', lead_path(lead), class: "btn btn-info", role: "button" %></td>
          <td><%= link_to 'Edit', edit_lead_path(lead), class: "btn btn-success", role: "button" %></td>
          <td><%= link_to 'Destroy', lead_path(lead), class: "btn btn-danger", role: "button",
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
</div>
<%= link_to 'Home', leads_path %>
<%= paginate @leads %>
</div>

app/views/leads/new.html.erb
<div class="container">
    <div class="container">
        <h1>New Lead</h1>
    </div>
    <div class="container">
        <%= form_for :lead, url: leads_path, html: {class: 'form-horizontal center'} do |f| %>
        
            <% if @lead.errors.any? %>
                <div id="error_explanation">
                  <h2>
                    <%= pluralize(@lead.errors.count, "error") %> prohibited
                    this lead from being saved:
                  </h2>
                  <ul>
                    <% @lead.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
             <% end %>
          
            <div class="form-group">
                <%= f.label :first_name, class: "col-md-2 control-label" %>
                <div class="col-md-8">
                    <%= f.text_field :first_name, class: "form-control" %>
                </div>
            </div>
            
            <div class="form-group">
                <%= f.label :last_name, class: "col-md-2 control-label" %>
                <div class="col-md-8">
                    <%= f.text_field :last_name, class: "form-control" %>
                </div>
            </div>
            
            <div class="form-group">
                <%= f.label :phone, class: "col-md-2 control-label" %>
                <div class="col-md-8">
                    <%= f.text_field :phone, class: "form-control" %>
                </div>
            </div>
            
            <div class="form-group">
                <%= f.label :email, class: "col-md-2 control-label" %>
                <div class="col-md-8">
                    <%= f.text_field :email, class: "form-control" %>
                </div>
            </div>
            
        <%= f.submit class: "btn btn-primary " %>
              
        <% end %>
    </div>
<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<div class="container">
    <div class="container">
        <h1>Lead Info</h1>
    </div>
    <div class="container">
        <p>
            <strong>First Name:</strong>
            <%= @lead.first_name %>
        </p>
        
        <p>
            <strong>Last Name:</strong>
            <%= @lead.last_name %>
        </p>
        
        <p>
            <strong>Phone Number:</strong>
            <%= @lead.phone %>
        </p>
        
        <p>
            <strong>Email Address:</strong>
            <%= @lead.email %>
        </p>
        
        <p>
            <strong>Contacted:</strong>
            <%= @lead.contacted? ? "yes" : "no" %>
        </p>
    </div>

    <%= link_to 'Edit', edit_lead_path(@lead) %>
    <%= link_to 'Back', leads_path %>
</div>

app/views/users/edit.html.erb
<div class="container">
    <div class="container">
        <h1>Update User</h1>
    </div>
    <div class="container">
    <%= form_for :user, url: user_path(@user), html: {class: 'form-horizontal center'}, method: :patch do |f| %>
        
        <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@user.errors.count, "error") %> prohibited
                this user from being saved:
              </h2>
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
         <% end %>
         
        <div class="form-group">
            <%= f.label :name, class: "col-md-2 control-label" %>
            <div class="col-md-8">
                <%= f.text_field :name, class: "form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :email, class: "col-md-2 control-label" %>
            <div class="col-md-8">
                <%= f.text_field :email, class: "form-control" %>
            </div>
        </div>
    
        <div class="form-group">
            <%= f.label :admin, class: "col-md-2 control-label" %>
            <div class="col-md-8">
                <%= f.check_box :admin, class: "form-control" %>
            </div>
        </div>
        
        <%= f.submit class: "btn btn-primary" %>
       
        <% end %>
    
    <%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
    <div class="container">
        <h1>Update User</h1>
    </div>
    <div class="container">    
        <table class="table-condensed table-hover table-responsive">
      <tr>
        <th>Name</th>
        <th>Email Address</th>
        <th>Admin Role</th>
      </tr>
     
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.admin? ? "yes" : "no" %></td>
              <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-success", role: "button" %></td>
              <td><%= link_to 'Destroy', user_path(user), class: "btn btn-danger", role: "button",
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </table>
        </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:
          </h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
     <% end %>
    
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    </p>
      <%= f.submit "Sign Up" %>
<% end %>
 

app/views/users/show.html.erb
<p>
    <strong>Name:</strong>
    <%= @user.name %>
</p>

<p>
    <strong>Email Address:</strong>
    <%= @user.email %>
</p>

<p>
    <strong>Admin Role:</strong>
    <%= @user.admin %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'Back', users_path %>